FROM apache/shardingsphere-proxy:5.3.2

ADD https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.3.0/mysql-connector-j-8.3.0.jar /opt/shardingsphere-proxy/ext-lib/

COPY conf/ /opt/shardingsphere-proxy/conf/
